# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  system-secret:
    type: string
    default: 'my-system-secret'
    description: System secret
  cookie-secret:
    type: string
    default: 'my-cookie-secret'
    description: Cookies secret
