options:
  login_ui_url:
    description: Kratos UI URL
    type: string
    default: "http://127.0.0.1:4455/"
  log_level:
    description: |
      The value controlling the verbosity of logs produced by Kratos.
      Available values are: panic, fatal, error, warn, info, debug, and trace.
    type: string
    default: "info"