options:
  login_ui_url:
    description: Kratos UI URL
    type: string
    default: "http://127.0.0.1:4455/"
  log_level:
    description: |
      The verbosity of logs produced by Hydra.
      Available values are: panic, fatal, error, warn, info, debug, and trace.
    type: string
    default: "info"
  dev:
    description:
      Run Hydra in dev mode, it is needed if HTTPS is not set up. This should only be used for development purposes.
    type: boolean
    default: False
