name: On Pull Request

# On pull_request, we:
# * always run lint checks
# * always run tests

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Install dependencies
        run: python3 -m pip install tox

      - name: Run linters
        run: tox -e lint

  tests:
    name: Run Tests
    needs:
      - lint
    uses: ./.github/workflows/tests.yaml
