name: On Push

# On push to a "special" branch, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests
# where a "special" branch is one of main/master or track/**, as
# by convention these branches are the source for a corresponding
# charmhub edge channel.

on:
  push:
    branches:
      - main
      - track/**

jobs:
  tests:
    name: Run Tests
    uses: ./.github/workflows/tests.yaml

  # publish runs in series with tests, and only publishes if tests passes
  publish-charm:
    name: Publish Charm
    needs: tests
    uses: ./.github/workflows/publish.yaml
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}

  publish-lib:
    name: Publish library
    needs: tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install charmcraft
        run: sudo snap install charmcraft --channel latest/stable --classic

      - name: Publish libs
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
        run: |
          charmcraft publish-lib charms.hydra.v0.hydra_endpoints
