# Release charm's libraries if they have changed
name: Release Libraries

on:
  push:
    branches:
      - main
    paths:
      - "lib/charms/hydra/**"

jobs:
  release-libs:
    name: Release any bumped library
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0
      - name: Release any bumped charm library
        uses: canonical/charming-actions/release-libraries@main
        with:
          credentials: "${{ secrets.CHARMCRAFT_CREDENTIALS }}"
          github-token: "${{ github.token }}"
