name: release

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - "track/**"

permissions:
    contents: write
    pull-requests: write

jobs:
  release:
      name: release
      uses: canonical/identity-team/.github/workflows/charm-release.yaml@dfa29853f47f32bbe2974ad021d067ae245452f8 # v1.7.5
      secrets:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
